identifier: zen
name: Corne-ish Zen
url: https://lowprokb.ca/collections/keyboards/products/corne-ish-zen
type: board
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - gpio
  - i2c
  - counter
  - spi
  - usb_device
  - lsm303dlhc
  - nvs
  - can
  - kscan
  - ble
