manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/johanfriis
  projects:
    - name: zmk
      remote: zmk
      revision: corne-ish_zen
      import: app/west.yml
  self:
    path: config
